[tools]

[[tools.gh]]
version = "latest"

[[tools.java]]
version = "openjdk-20.0.2"

[[tools.jq]]
version = "latest"

[[tools.node]]
version = "latest"

[[tools.ruby]]
version = "latest"

[[tools.rust]]
version = "latest"
components = "rust-src,llvm-tools"
